import { Head, router, useForm } from "@inertiajs/react";
import { Plus, Search, ShieldCheck, Wrench, X } from "lucide-react";
import type { FormEvent} from "react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import SearchableProductSelect from "@/components/SearchableProductSelect";
import AdminLayout from "@/layouts/AdminLayout";

type UnitOption = { id: number; label: string; sale_id: number | null; customer_id: number | null; customer_name: string | null; warranty_active: boolean; warranty_expires_at: string | null };
type RecordItem = { id: number; service_number: string; device_unit_id: number; device: string; identifier: string; customer: string | null; customer_phone: string | null; branch: string; service_type: string; status: string; warranty_covered: boolean; issue: string; diagnosis: string | null; resolution: string | null; technician: string | null; amount: number; received_at: string; completed_at: string | null; notes: string | null };
type Props = { records: { data: RecordItem[]; links: { url: string | null; label: string; active: boolean }[] }; units: UnitOption[]; filters: { search?: string; status?: string } };
const input = "h-10 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:ring-1 focus:ring-primary";
const statuses = ['received','diagnosing','waiting_parts','in_progress','ready','completed','cancelled'];

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onMouseDown={onClose}><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl border border-border bg-card" onMouseDown={e => e.stopPropagation()}><div className="flex items-center justify-between border-b border-border p-4"><h2 className="font-bold">{title}</h2><button onClick={onClose}><X className="h-4 w-4" /></button></div>{children}</div></div>; }

export default function DeviceServicesIndex({ records, units, filters }: Props) {
    const [showAdd, setShowAdd] = useState(false); const [editing, setEditing] = useState<RecordItem | null>(null); const [search, setSearch] = useState(filters.search ?? ""); const [status, setStatus] = useState(filters.status ?? "");
    const create = useForm({ device_unit_id: "", service_type: "warranty_claim", issue: "", technician: "", amount: "0", notes: "" });
    const edit = useForm({ status: "received", diagnosis: "", resolution: "", technician: "", amount: "0", notes: "" });
    const selected = units.find(u => String(u.id) === create.data.device_unit_id);
    const filter = (patch: Record<string,string>) => router.get('/device-services', { search, status, ...patch }, { preserveState: true, replace: true });
    const submitCreate = (e: FormEvent) => { e.preventDefault(); create.post('/device-services', { onSuccess: () => { setShowAdd(false); create.reset(); } }); };
    const openEdit = (r: RecordItem) => { setEditing(r); edit.setData({ status: r.status, diagnosis: r.diagnosis ?? '', resolution: r.resolution ?? '', technician: r.technician ?? '', amount: String(r.amount), notes: r.notes ?? '' }); };
    const submitEdit = (e: FormEvent) => { e.preventDefault(); if (!editing) return; edit.patch(`/device-services/${editing.id}`, { onSuccess: () => setEditing(null) }); };

    return <AdminLayout><Head title="Warranty & Repairs" /><div className="mx-auto max-w-[1500px] space-y-5 p-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold">Warranty & After-sales</h1><p className="text-xs text-muted-foreground">Claims, diagnostics, repairs, returns, and complete device history.</p></div><Button onClick={() => setShowAdd(true)}><Plus className="mr-2 h-4 w-4" />New service job</Button></div>
    <div className="flex flex-wrap gap-2 rounded-xl border border-border bg-card p-3"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><input className={`${input} pl-9`} value={search} onChange={e => setSearch(e.target.value)} onKeyDown={e => e.key === 'Enter' && filter({ search })} placeholder="Job number, customer, IMEI, serial" /></div><select className={`${input} w-auto`} value={status} onChange={e => { setStatus(e.target.value); filter({ status: e.target.value }); }}><option value="">All statuses</option>{statuses.map(s => <option key={s} value={s}>{s.replace('_',' ')}</option>)}</select><Button variant="outline" onClick={() => filter({ search })}>Search</Button></div>
    <div className="grid gap-3">{records.data.map(r => <button key={r.id} onClick={() => openEdit(r)} className="rounded-xl border border-border bg-card p-4 text-left transition-colors hover:border-primary/50"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-lg bg-primary/10 p-2 text-primary">{r.service_type === 'warranty_claim' ? <ShieldCheck className="h-5 w-5" /> : <Wrench className="h-5 w-5" />}</div><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{r.service_number}</p><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] uppercase">{r.status.replace('_',' ')}</span>{r.warranty_covered && <span className="rounded-full bg-emerald-500/15 px-2 py-0.5 text-[10px] text-emerald-500">Warranty covered</span>}</div><p className="text-sm">{r.device} · <span className="font-mono text-primary">{r.identifier}</span></p><p className="mt-1 text-xs text-muted-foreground">{r.customer ?? 'Walk-in'} · {r.branch} · Received {new Date(r.received_at).toLocaleString()}</p></div></div><div className="text-right"><p className="font-semibold">₱{r.amount.toLocaleString(undefined,{minimumFractionDigits:2})}</p><p className="text-xs text-muted-foreground">{r.technician ?? 'Unassigned'}</p></div></div><p className="mt-3 border-t border-border pt-3 text-sm"><span className="text-muted-foreground">Issue: </span>{r.issue}</p></button>)}{records.data.length === 0 && <div className="rounded-xl border border-border bg-card p-12 text-center text-muted-foreground">No service records found.</div>}</div>
    <div className="flex gap-1">{records.links.map((l,i) => <button key={i} disabled={!l.url} onClick={() => l.url && router.get(l.url)} className={`rounded px-3 py-1 text-xs ${l.active ? 'bg-primary text-primary-foreground' : 'border border-border'} disabled:opacity-40`} dangerouslySetInnerHTML={{__html:l.label}} />)}</div></div>
    {showAdd && <Modal title="Receive device for service" onClose={() => setShowAdd(false)}><form onSubmit={submitCreate} className="space-y-4 p-4"><div className="block text-xs">Sold device<SearchableProductSelect products={units.map(u => ({ ...u, name: `${u.label} — ${u.customer_name ?? 'Walk-in'}` }))} value={create.data.device_unit_id} onChange={value => create.setData('device_unit_id', value)} placeholder="Select by device / IMEI / serial" searchPlaceholder="Search device, IMEI, serial, or customer…" className="mt-1" /><span className="text-destructive">{create.errors.device_unit_id}</span></div>{selected && <div className={`rounded-lg border p-3 text-xs ${selected.warranty_active ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-600' : 'border-amber-500/30 bg-amber-500/10 text-amber-600'}`}>{selected.warranty_active ? `Warranty active until ${selected.warranty_expires_at}` : 'Warranty is expired or unavailable.'}</div>}<label className="block text-xs">Service type<select className={`${input} mt-1`} value={create.data.service_type} onChange={e => create.setData('service_type', e.target.value)}><option value="warranty_claim">Warranty claim</option><option value="repair">Paid repair</option><option value="return">Return / replacement</option></select></label><label className="block text-xs">Reported issue<textarea className="mt-1 min-h-24 w-full rounded-lg border border-border bg-background p-3 text-sm" value={create.data.issue} onChange={e => create.setData('issue', e.target.value)} required /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">Technician<input className={`${input} mt-1`} value={create.data.technician} onChange={e => create.setData('technician', e.target.value)} /></label><label className="text-xs">Quoted amount<input type="number" min="0" step="0.01" className={`${input} mt-1`} value={create.data.amount} onChange={e => create.setData('amount', e.target.value)} /></label></div><label className="block text-xs">Notes<input className={`${input} mt-1`} value={create.data.notes} onChange={e => create.setData('notes', e.target.value)} /></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setShowAdd(false)}>Cancel</Button><Button disabled={create.processing}>Create service job</Button></div></form></Modal>}
    {editing && <Modal title={editing.service_number} onClose={() => setEditing(null)}><form onSubmit={submitEdit} className="space-y-4 p-4"><div className="rounded-lg bg-muted/40 p-3 text-sm"><p className="font-semibold">{editing.device} · <span className="font-mono">{editing.identifier}</span></p><p className="text-xs text-muted-foreground">{editing.issue}</p></div><label className="block text-xs">Status<select className={`${input} mt-1`} value={edit.data.status} onChange={e => edit.setData('status', e.target.value)}>{statuses.map(s => <option key={s} value={s}>{s.replace('_',' ')}</option>)}</select></label><label className="block text-xs">Diagnosis<textarea className="mt-1 min-h-20 w-full rounded-lg border border-border bg-background p-3 text-sm" value={edit.data.diagnosis} onChange={e => edit.setData('diagnosis', e.target.value)} /></label><label className="block text-xs">Resolution<textarea className="mt-1 min-h-20 w-full rounded-lg border border-border bg-background p-3 text-sm" value={edit.data.resolution} onChange={e => edit.setData('resolution', e.target.value)} /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">Technician<input className={`${input} mt-1`} value={edit.data.technician} onChange={e => edit.setData('technician', e.target.value)} /></label><label className="text-xs">Final amount<input type="number" min="0" step="0.01" className={`${input} mt-1`} value={edit.data.amount} onChange={e => edit.setData('amount', e.target.value)} /></label></div><label className="block text-xs">Notes<input className={`${input} mt-1`} value={edit.data.notes} onChange={e => edit.setData('notes', e.target.value)} /></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancel</Button><Button disabled={edit.processing}>Update job</Button></div></form></Modal>}
    </AdminLayout>;
}
